# Use the official AWS Lambda Python base image
FROM public.ecr.aws/lambda/python:3.12

# Set the working directory
WORKDIR ${LAMBDA_TASK_ROOT}

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV COLUMNS=120

# Install uv
RUN pip install uv

# Copy the entire package
COPY requirements.txt ./
COPY ./parliament_mcp ./parliament_mcp

# Install dependencies
RUN uv pip install --system -r requirements.txt

# Set the command to run the handler
CMD [ "parliament_mcp.lambda_handler.handler" ]
